name: github ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dmaven.test.skip=true verify

  test:
    name: Test API
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Automation
        run: mvn clean verify

